#!/usr/bin/env bash

echo
echo "--------> git branch <--------"
echo

# The command's description
printf "%s\n\t%s\n\n" "Description:" ""

# The command's syntax
printf "%s\t%s\n" "Syntax:" ""
printf "\n"
printf "\t%s\n\n" ""

# The command's usage examples
printf "%s\n" "Usage:"
printf "\t%s\n" "~/ ➜ git branch --track a-branch git@github.com/octocat/test.git"
printf "\t%s\n\n" "~/ ➜ git branch --all"

exit 0
