#!/usr/bin/env bash

echo "--------> clear <--------"

# The command's description
echo -e "\nDescription: \n\tClear your screen if it is possible.  It looks in the environment for the terminal type and
\tthen in the terminfo database to figure out how to clear the screen. Clear ignores any command-line parameters
\tthat may be present."

echo "--------------"
# The command's syntax
echo "Syntax: clear"

echo "--------------"
# The command's usage
echo "Usage:"


exit 0
