#!/usr/bin/env bash

echo "--------> ls <--------"

# The command's description
echo -e "\nDescription:\n\tList directory contents. List information about the FILEs (the current directory by default)."
echo -e "\n\tNOTE: If no option or directory is give, 'ls' will print the contents of the current directory in vertical columns alphabetically"

echo "--------------"
# The command's syntax
echo "Syntax: ls [-ABCFGHLOPRSTUW@abcdefghiklmnopqrstuwx1] [directory ...]"
echo -e "\n\t-@   Display extended attribute keys and sizes in long (-l) output.

\t-1   (The numeric digit ''one''.)  Force output to be one entry per line.  This is the default when output is not to a
\t     terminal.

\t-A   List all entries except for . and ...  Always set for the superuser.

\t-a   Include directory entries whose names begin with a dot (.).

\t-B   Force printing of non-printable characters (as defined by ctype(3) and current locale settings) in file names as
\t     xxx, where xxx is the numeric value of the character in octal.

\t-b   As -B, but use C escape codes whenever possible.

\t-C   Force multi-column output; this is the default when output is to a terminal.

\t-c   Use time when file status was last changed for sorting (-t) or long printing (-l).

\t-d   Directories are listed as plain files (not searched recursively).

\t-e   Print the Access Control List (ACL) associated with the file, if present, in long (-l) output.

\t-F   Display a slash ('/') immediately after each pathname that is a directory, an asterisk ('*') after each that is
\t     executable, an at sign ('@') after each symbolic link, an equals sign ('=') after each socket, a percent sign ('%')
\t     after each whiteout, and a vertical bar ('|') after each that is a FIFO.

\t-f   Output is not sorted.  This option turns on the -a option.

\t-G   Enable colorized output.  This option is equivalent to defining CLICOLOR in the environment.

\t-g   This option is only available for compatibility with POSIX; it is used to display the group name in the long (-l)
\t     format output (the owner name is suppressed).

\t-H   Symbolic links on the command line are followed.  This option is assumed if none of the -F, -d, or -l options are
\t     specified.

\t-h   When used with the -l option, use unit suffixes: Byte, Kilobyte, Megabyte, Gigabyte, Terabyte and Petabyte in
\t     order to reduce the number of digits to three or less using base 2 for sizes.

\t-i   For each file, print the file's file serial number (inode number).

\t-k   If the -s option is specified, print the file size allocation in kilobytes, not blocks.  This option overrides
\t     the environment variable BLOCKSIZE.

\t-L   Follow all symbolic links to final target and list the file or directory the link references rather than the link
\t     itself.  This option cancels the -P option.

\t-l   (The lowercase letter ''ell''.)  List in long format.  (See below.)  If the output is to a terminal, a total sum
\t     for all the file sizes is output on a line before the long listing.

\t-m   Stream output format; list files across the page, separated by commas.

\t-n   Display user and group IDs numerically, rather than converting to a user or group name in a long (-l) output.
\t     This option turns on the -l option.

\t-O   Include the file flags in a long (-l) output.

\t-o   List in long format, but omit the group id.

\t-P   If argument is a symbolic link, list the link itself rather than the object the link references.  This option
\t     cancels the -H and -L options.

\t-p   Write a slash ('/') after each filename if that file is a directory.

\t-q   Force printing of non-graphic characters in file names as the character '?'; this is the default when output is
\t     to a terminal.

\t-R   Recursively list subdirectories encountered.

\t-r   Reverse the order of the sort to get reverse lexicographical order or the oldest entries first (or largest files
\t     last, if combined with sort by size

\t-S   Sort files by size

\t-s   Display the number of file system blocks actually used by each file, in units of 512 bytes, where partial units
\t     are rounded up to the next integer value.  If the output is to a terminal, a total sum for all the file sizes is output
\t     on a line before the listing.  The environment variable BLOCKSIZE overrides the unit size of 512 bytes.

\t-T   When used with the -l (lowercase letter ''ell'') option, display complete time information for the file,
\t     including month, day, hour, minute, second, and year.

\t-t   Sort by time modified (most recently modified first) before sorting the operands by lexicographical order.

\t-u   Use time of last access, instead of last modification of the file for sorting (-t) or long printing (-l).

\t-U   Use time of file creation, instead of last modification for sorting (-t) or long output (-l).

\t-v   Force unedited printing of non-graphic characters; this is the default when output is not to a terminal.

\t-W   Display whiteouts when scanning directories. (-S) flag).

\t-w   Force raw printing of non-printable characters.  This is the default when output is not to a terminal.

\t-x   The same as -C, except that the multi-column output is produced with entries sorted across, rather than down, the
\t     columns.



\tThe Long Format

         If the -l option is given, the following information is displayed for each file: file mode, number of links,
         owner name, group name, number of bytes in the file, abbreviated month, day-of-month file was last modified,
         hour file last modified, minute file last modified, and the pathname.  In addition, for each directory whose
         contents are displayed, the total number of 512-byte blocks used by the files in the directory is displayed on
         a line by itself, immediately before the information for the files in the directory.  If the file or directory
         has extended attributes, the permissions field printed by the -l option is followed by a '@' character.
         Otherwise, if the file or directory has extended security information (such as an access control list), the
         permissions field printed by the -l option is followed by a '+' character.

         If the modification time of the file is more than 6 months in the past or future, then the year of the last
         modification is displayed in place of the hour and minute fields.

         If the owner or group names are not a known user or group name, or the -n option is given, the numeric ID's are
         displayed.

         If the file is a character special or block special file, the major and minor device numbers for the file are
         displayed in the size field.  If the file is a symbolic link, the pathname of the linked-to file is preceded
         by ``->''.

         The file mode printed under the -l option consists of the entry type, owner permissions, and group permissions.
         The entry type character describes the type of file, as follows:

               b     Block special file.
               c     Character special file.
               d     Directory.
               l     Symbolic link.
               s     Socket link.
               p     FIFO.
               -     Regular file.

         The next three fields are three characters each: owner permissions, group permissions, and other permissions.
         Each field has three character positions:

               1.   If r, the file is readable; if -, it is not readable.

               2.   If w, the file is writable; if -, it is not writable.

               3.   The first of the following that applies:

                          S     If in the owner permissions, the file is not exe-
                                cutable and set-user-ID mode is set.  If in the
                                group permissions, the file is not executable and
                                set-group-ID mode is set.

                          s     If in the owner permissions, the file is exe-
                                cutable and set-user-ID mode is set.  If in the
                                group permissions, the file is executable and set-
                                group-ID mode is set.

                          x     The file is executable or the directory is search-
                                able.

                              The file is neither readable, writable, exe-
                                cutable, nor set-user-ID nor set-group-ID mode,
                                nor sticky.  (See below.)

                    These next two apply only to the third character in the last
                    group (other permissions).

                          T     The sticky bit is set (mode 1000), but not execute
                                or search permission.  (See chmod(1) or
                                sticky(8).)

                          t     The sticky bit is set (mode 1000), and is search-
                                able or executable.  (See chmod(1) or sticky(8).)"

echo "--------------"
# The command's usage
echo "Usage:"


exit 0
