#!/usr/bin/env bash

echo "--------> mkdir <--------"

# The command's description
echo -e "\nDescription: \n\tThe mkdir utility creates directories that do not already exist. The user must have write
\tpermission in the parent directory."

echo "--------------"
# The command's syntax
echo "Syntax: mkdir [-pv] [-m mode] directory ..."
echo -e "\n     -m mode
             Set the file permission bits of the final created directory to the specified mode.  The mode argument can be in any of the
             formats specified to the chmod(1) command.  If a symbolic mode is specified, the operation characters ''+'' and ''-'' are
             interpreted relative to an initial mode of ''a=rwx''.

     -p      Create intermediate directories as required.  If this option is not specified, the full path prefix of each given parameter must already
             exist.  On the other hand, with this option specified, no error will be reported if a directory given as a parameter already
             exists.  Intermediate directories are created with permission bits of rwxrwxrwx (0777), plus write and search permission for the owner.

     -v      Be verbose when creating directories, listing them as they are created."

echo "--------------"
# The command's usage
echo "Usage:"


exit 0
