#!/usr/bin/env bash

echo "--------> more <--------"

# The command's description
echo -e "\nDescription: \n\tMore pages through text, from file, one screenful at a time. This version is
\tespecially primitive. Users should realize that less(1) provides more(1) emulation plus extensive enhancements."
echo -e "\n\tNOTE: You can't scroll back up once it has left the screen."

echo "--------------"
# The command's syntax
echo "Syntax: more [options] file..."
echo -e "\n\t-d    Prompt with "[Press space to continue, 'q' to quit.]", and
              display "[Press 'h' for instructions.]" instead of ringing the
              bell when an illegal key is pressed.

        -l    Do not pause after any line containing a ^L (form feed).

        -f    Count logical lines, rather than screen lines (i.e., long
              lines are not folded).

        -p    Do not scroll.  Instead, clear the whole screen and then
              display the text.  Notice that this option is switched on
              automatically if the executable is named page.

        -c    Do not scroll.  Instead, paint each screen from the top,
              clearing the remainder of each line as it is displayed.

        -s    Squeeze multiple blank lines into one.

        -u    Suppress underlining.

        -number
              The screen size to use, in number of lines.

        +number
              Start displaying each file at line number.

        +/string
              The string to be searched in each file before starting to
              display it."

echo "--------------"
# The command's usage
echo "Usage:"


exit 0
