#!/usr/bin/env bash

echo "--------> rmdir <--------"

# The command's description
echo -e "\nDescription: \n\tRemove directories that are empty. Arguments are processed in the order given."

echo "--------------"
# The command's syntax
echo "Syntax: rmdir [-p] directory ..."
echo -e "\n \t-p      Each directory argument is treated as a pathname of which all components will be removed, if they
                are empty, starting with the last most component.  (See rm(1) for fully non-discriminant recursive removal.)"

echo "--------------"
# The command's usage
echo "Usage:"


exit 0
