#!/usr/bin/env bash

echo "--------> touch <--------"

# The command's description
echo -e "\ndescription here\n"

echo "--------------"
# The command's syntax
echo "Syntax:"

echo "--------------"
# The command's usage
echo "Usage:"
